---
- hosts: 18.215.148.108
  become: yes
  tasks:
    - name: install httpd
      yum: name=httpd state=present
    - name: copy html
      copy: src=index.html dest=/var/www/html
    - name: starting httpd
      service: name=httpd state=started
